wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648295534
    t:
      1:
      - 1
      - 41
      3:
      - 13
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 5
dataset:
  desc: null
  value: FashionMNIST
epochs:
  desc: null
  value: 100
hidden_units:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.25
p_hidden:
  desc: null
  value: 0
p_in:
  desc: null
  value: 0
